### ISSUE TITLE
Data grid view not updated in return userform 

### ISSUE THREAD

**Issue by issamzen** [g3ntz/Premium-RentACar-Desktop-App#1]
Hello Brother,

many thanks for your project it was awsome in all way nothing to say .

I have just one issue please the datagridview in return could not be updated I didn't change anything in the code . but not working.

exactly from (FrmReturnCRUD) to (returns in dashboard)
could you tell me way plase ? 

best regards

**Comment by g3ntz** [comment]
Hello Issamzen,

I'm glad my project helped you.

I just fixed the issue but the fix is not included in app setup. It's been a long time since I worked on this project and the bunifu license it's not working for the older version that I used back then, although I fixed this issue I couldn't update the setup.

If you find a way around, then great  :)

Best regards

**Comment by issamzen** [comment]
If I can just  meet you I will give you a big gift. Many thanks brother.

From Morocco to you thank you very much brother.

I will try it today. You helped me a lot.

my brother have this project and want any software to help him to manage
the rental. I look to any project a lot. I found that expensif. And i am
not f1milair with C#. So when I see your project I cried it's like a
miracle. It's free it's amasing.


Thank you the simple thing I can give you for your hard work

Le dim. 31 oct. 2021 à 16:58, Gentrit Mushica ***@***.***> a
écrit :
